modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
#issueTrackerURL=""

[[mods]]
    modId="schematicprinter"
    version="${file.jarVersion}"
    displayName="Schematic Printer"
    #updateJSONURL=""
    authors="Grimmauld"
    description='''
Some cool description'''

[[dependencies.schematicprinter]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.schematicprinter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"