modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
#issueTrackerURL=""

[[mods]]
    modId="schematicprinter"
    version="0.0.1"
    displayName="Schematic Printer"
    #updateJSONURL=""
    authors="Grimmauld"
    description='''
Some cool description'''

[[dependencies.schematicprinter]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.schematicprinter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"